FROM ubuntu:18.04
ENV TZ=Europe/Moscow
ENV MAVEN_OPTS="--add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.text=ALL-UNNAMED --add-opens java.desktop/sun.awt=ALL-UNNAMED"

RUN mkdir study-service
WORKDIR ./study-service

COPY /study-service .

RUN apt-get update
RUN apt-get install openjdk-17-jdk openjdk-17-jre -y
RUN apt-get install maven -y
RUN mvn clean install  -Dmaven.test.skip=true
CMD ["mvn", "spring-boot:run"]
