<<<<<<< HEAD
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: user_route
          uri: http://localhost:8082
          predicates:
            - Path=/api/user/**
        - id: news_route
          uri: http://localhost:8081
          predicates:
            - Path=/api/news/**
        - id: study_route
          uri: http://localhost:8083
          predicates:
            - Path=/api/study/**



server:
  port: 8080
=======
>>>>>>> dev

