server:
  port:
    8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/jabka_user
    username: jabka
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
    properties:
      hibernate:
      format_sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQL95Dialect
#      TODO: создать почту
  mail:
    host: smtp.yandex.ru
    port: 465
    protocol: smtps
    username:
    password:
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
        ssl:
          enable: true
        sender:
          email:

mail-service:
  activation:
    uri: http://localhost:8080/api/auth/activation?id={id}


jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
  lifetime: 2h

logging:
  level:
    org:
      springframework:
        security: DEBUG