server:
  port:
    8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/jabka_user
    username: jabka
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
    properties:
      hibernate:
      format_sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQL95Dialect