openapi: 3.0.0
info:
  title: Study API
  version: 0.0.1
servers:
  - url: http://localhost:8083/api
paths:
  /schedule:
    get:
      security:
        - bearerAuth: [ ]
      summary: Get All Schedule
      tags:
        - Schedule
      operationId: getAllSchedule
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ScheduleOpenAPI"
        '400':
          description: Bad Request
        '401':
          $ref: "#/components/responses/UnauthorizedError"
        '403':
          description: Do Not Have Necessary Rights to Execute This Operation
        '404':
          description: Not Found
    post:
      security:
        - bearerAuth: [ ]
      summary: Create a Schedule
      tags:
        - Schedule
      operationId: createSchedule
      requestBody:
        description: Schedule Object
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScheduleOpenAPI'
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          description: Do Not Have Necessary Rights to Execute This Operation

  /schedule/{id}:
    get:
      security:
        - bearerAuth: [ ]
      summary: Schedule Information by Id
      tags:
        - Schedule
      operationId: getScheduleByGroup
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            format: int64
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ScheduleOpenAPI"
        '401':
          $ref: "#/components/responses/UnauthorizedError"
        '403':
          description: Do Not Have Necessary Rights to Execute This Operation
        '404':
          description: Not Found
    delete:
      security:
        - bearerAuth: [ ]
      summary: Delete a Schedule by Id
      tags:
        - Schedule
      operationId: deleteSchedule
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            format: int64
          required: true
      responses:
        '200':
          description: Deleted
        '400':
          description: Bad Request
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          description: Do Not Have Necessary Rights to Execute This Operation
    put:
      security:
        - bearerAuth: [ ]
      summary: Update a Schedule by Id
      tags:
        - Schedule
      operationId: updateSchedule
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            format: int64
          required: true
      requestBody:
        description: Schedule Object
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScheduleOpenAPI'
      responses:
        '200':
          description: Updated
        '400':
          description: Bad Request
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          description: Do Not Have Necessary Rights to Execute This Operation

  /schedule/professor:
    get:
      security:
        - bearerAuth: [ ]
      summary: Get Schedule By Professor Id
      tags:
        - Schedule
      operationId: getScheduleByProfessorId
      parameters:
        - in: query
          name: professorId
          schema:
            type: integer
            format: int64
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ScheduleOpenAPI"
        '400':
          description: Bad Request
        '401':
          $ref: "#/components/responses/UnauthorizedError"
        '403':
          description: Do Not Have Necessary Rights to Execute This Operation
        '404':
          description: Not Found

  /group/{id}:
    get:
      security:
        - bearerAuth: [ ]
      summary: Group Information
      tags:
        - Group
      operationId: getGroupById
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            format: int64
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StudyGroupOpenAPI"
        '401':
          $ref: "#/components/responses/UnauthorizedError"
        '403':
          description: Do Not Have Necessary Rights to Execute This Operation
        '404':
          description: Not Found
    delete:
      security:
        - bearerAuth: [ ]
      summary: Delete a Group By Id
      tags:
        - Group
      operationId: deleteGroupById
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            format: int64
          required: true
      responses:
        '200':
          description: Deleted
        '400':
          description: Bad Request
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          description: Do Not Have Necessary Rights to Execute This Operation

  /group:
    get:
      security:
        - bearerAuth: [ ]
      summary: All Groups Information
      tags:
        - Group
      operationId: getAllGroups
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/StudyGroupOpenAPI"
        '401':
          $ref: "#/components/responses/UnauthorizedError"
        '403':
          description: Do Not Have Necessary Rights to Execute This Operation
        '404':
          description: Not Found
    post:
      security:
        - bearerAuth: [ ]
      summary: Create a Group
      tags:
        - Group
      operationId: createGroup
      requestBody:
        description: Group Object
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StudyGroupOpenAPI'
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          description: Do Not Have Necessary Rights to Execute This Operation

  /materials:
    get:
      security:
        - bearerAuth: [ ]
      summary: All Materials Information
      tags:
        - Materials
      operationId: getAllMaterials
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/StudyMaterialsOpenAPI"
        '401':
          $ref: "#/components/responses/UnauthorizedError"
        '403':
          description: Do Not Have Necessary Rights to Execute This Operation
        '404':
          description: Not Found
    post:
      security:
        - bearerAuth: [ ]
      summary: Create a Material
      tags:
        - Materials
      operationId: createMaterials
      requestBody:
        description: Materials Object
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StudyMaterialsOpenAPI'
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          description: Do Not Have Necessary Rights to Execute This Operation

  /materials/{id}:
    get:
      security:
        - bearerAuth: [ ]
      summary: Materials Information
      tags:
        - Materials
      operationId: getMaterialsById
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            format: int64
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StudyMaterialsOpenAPI"
        '401':
          $ref: "#/components/responses/UnauthorizedError"
        '403':
          description: Do Not Have Necessary Rights to Execute This Operation
        '404':
          description: Not Found
    put:
      security:
        - bearerAuth: [ ]
      summary: Update a Materials
      tags:
        - Materials
      operationId: updateMaterials
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            format: int64
          required: true
      requestBody:
        description: Materials Object
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StudyMaterialsOpenAPI'
      responses:
        '200':
          description: Updated
        '400':
          description: Bad Request
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          description: Do Not Have Necessary Rights to Execute This Operation
    delete:
      security:
        - bearerAuth: [ ]
      summary: Delete a Material by Id
      tags:
        - Materials
      operationId: deleteMaterials
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            format: int64
          required: true
      responses:
        '200':
          description: Deleted
        '400':
          description: Bad Request
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          description: Do Not Have Necessary Rights to Execute This Operation



components:
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:

    ScheduleOpenAPI:
      type: object
      required:
        - dateTime
        - studyGroup
        - subject
        - classFormat
        - professor
      properties:
        id:
          type: integer
          format: int64
        date:
          type: string
          format: date-time
        studyGroup:
          type: object
          $ref: "#/components/schemas/StudyGroupOpenAPI"
        subject:
          type: object
          $ref: "#/components/schemas/SubjectOpenAPI"
        classFormat:
          type: object
          $ref: "#/components/schemas/ClassFormat"
        auditorium:
          type: string
        linkForTheClass:
          type: string
        professor:
          type: object
          $ref: "#/components/schemas/ProfessorSubjectOpenAPI"

    StudyGroupOpenAPI:
      type: object
      required:
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string

    SubjectOpenAPI:
      type: object
      required:
        - name
        - studyGroup
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        studyGroup:
          type: object
          $ref: "#/components/schemas/StudyGroupOpenAPI"
        studyMaterials:
          type: object
          $ref: "#/components/schemas/StudyMaterialsOpenAPI"
        schedule:
          type: object
          $ref: "#/components/schemas/ScheduleOpenAPI"

    ProfessorSubjectOpenAPI:
      type: object
      required:
        - subjectId
        - professorId
      properties:
        subjectId:
          type: integer
          format: int64
        professorId:
          type: integer
          format: int64

    ClassFormat:
      type: string
      enum:
        - IN_PERSON
        - DISTANT

    StudyMaterialsType:
      type: string
      enum:
        - MATERIAL
        - TASK

    StudyMaterialsOpenAPI:
      type: object
      required:
        - studyMaterialsType
        - subject
        - materialsText
      properties:
        id:
          type: integer
          format: int64
        studyMaterialsType:
          type: object
          $ref: "#/components/schemas/StudyMaterialsType"
        materialsText:
          type: string
        subject:
          type: object
          $ref: "#/components/schemas/SubjectOpenAPI"
        homework:
          type: object
          $ref: "#/components/schemas/HomeworkOpenAPI"

    HomeworkOpenAPI:
      type: object
      required:
        - studyMaterials
      properties:
        id:
          type: integer
          format: int64
        studyMaterials:
          type: object
          $ref: "#/components/schemas/StudyMaterialsOpenAPI"


