openapi: 3.0.0
info:
  title: Study API
  version: 0.0.1
servers:
  - url: http://localhost:8083/api
paths:
  /schedule:
    get:
      summary: Schedule Information
      tags:
        - Schedule
      operationId: getSchedule
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ScheduleOpenAPI"
        '401':
          $ref: "#/components/responses/UnauthorizedError"
        '404':
          description: Not Found

components:
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    ScheduleOpenAPI:
      type: object
      required:
        - date
        - time
        - group
        - subject
        - classFormat
        - auditorium
        - linkForTheClass
      properties:

